falak.exe: Driver.cs Scanner.cs Token.cs TokenCategory.cs Parser.cs \
	SyntaxError.cs Node.cs SpecificNodes.cs SemanticVisitor.cs \
	SemanticError.cs Type.cs WatVisitor.cs

	mcs -out:falak.exe Driver.cs Scanner.cs Token.cs TokenCategory.cs Parser.cs \
	SyntaxError.cs Node.cs SpecificNodes.cs SemanticVisitor.cs \
	SemanticError.cs Type.cs WatVisitor.cs

clean:


	rm -f falak.exe
